spring:
  datasource:
    url: jdbc:mysql://localhost:3306/video_store_exam?createDatabaseIfNotExist=true&autoReconnect=true&useSLL=false&useLegacyDatetimeCode=false

    username: root
    password: Petrucci93.
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'
  output:
    ansi:
      enabled: ALWAYS
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        globally_quoted_identifiers = "true"
    show-sql: true
logging:
  level:
    it.develhope.StudioMedico.serviceImpl: ERROR

spring-doc:
  # Enable/Disable the swagger-ui
  swagger-ui:
    enabled: true
  # Enable/Disable the /v3/api-docs endpoint
  api-docs:
    enabled: true

